### ISSUE TITLE
[Info]: Deployment version 3.5.1

### ISSUE THREAD

**Issue by HeropolisDa2ny** [okadan/flutter-nfc-manager#227]
Hello, I would like to know when are you going to deploy your version 3.5.1 ? Because it seems like the patch made on this version for the problem related to Kotlin error (`.pub-cache/hosted/pub.dev/nfc_manager-3.5.0/android/src/main/kotlin/io/flutter/plugins/nfcmanager/Translator.kt:43:15 'fun String.toLowerCase(locale: Locale): String' is deprecated. Use lowercase() instead.`) fixes the blocking build on the new flutter+kotlin versions.
So it would be great to have a new version if it is ready instead of being forced to use your package directly from github :
```
  # ! When version ^3.5.1 >= switch to that version
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager
```

Thank you for your time 🙏

**Comment by DavidProdinger** [comment]
Yes, this issue was fixed in #215

@okadan just needs to publish it to [pub.dev](https://pub.dev/packages/nfc_manager), changelog and version is already adjusted for the release.

**Comment by reyhanlioglu** [comment]
hi @DavidProdinger ,

When will you publish this version? Thanks

**Comment by dominikIncibit** [comment]
same issue here? Any workaround?

**Comment by philitell** [comment]
Seems the version has never been released

**Comment by HeropolisDa2ny** [comment]
@philitell It just seems that @okadan doesn't wanna continue maintaining the package since he doesn't approve PR meant to fix bugs nor reply to issues. However he updated recently the packages / flutter version. It's quite weird.

**Comment by DavidProdinger** [comment]
You can install directly from the commit like this: (fixed in PR #215)
```yaml
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      ref: effaff035be1a80b02f72b6422e7be9ba6fa5b42
```

The releases on [pub.dev](https://pub.dev/packages/nfc_manager/versions) went ahead with the `4.0.x` branch with breaking changes.
